language: php
php:
- '7.0'
- '7.1'
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
install:
- composer install
- composer require "satooshi/php-coveralls" "^1" --dev --no-update
- "./frameworks/phifty/travis/install"
before_script:
- "./frameworks/phifty/travis/before_script"
- phpenv rehash
- "./travis/before_script"
- php vendor/bin/phifty asset --link
script:
- time php bootstrap.php
- phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
  - exts
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: BKEwSxE4OIT0Gk1uwLWrV6hXE9oRMCZDJjOqKlvZn0eBFeurDEH107Y4DxZ3pcLJ5BwHqFRpwxqyBEPeAxcxJYgQs9wq7WAJrOrojXDKoip1wF6QP4SjYzlq6vgnlrfsxmill0dK9X7+DnKopWjzh/LWZzMITxvfmg0CHrYwRZBPvZFt8bntDLNDUqItIZbRqpJmDiV2HmHjaBrygYzBcfEYWgfzpZAQdtT7VeubQ7VI2UI05zm4zTUnTVgiFxxLmUpFOR6xrKx4DKinsFRWrYhOZ2QEVX2kr3HvQcd9KxRBcv/1FJaH4KGAqG4swnxNusSnwvz+ATY1EZMkTtINl+s7eNTozvzTC7Pxl1X6feXKoivk32m4XKG2vT/dFOPfbjhZJoGeb3fdjZAya7t40tCmUOd3oSSf7QjWcCrEPM6NverwBjfdbFxtg12aqoBrvAKIViLo/qktxWjkWQtUMaDTjVmtK4QoCJrQTgqRsld8BN+FJbR0JokH1V7P0a1YJ36moU1kUN7GNC8Xkrl4EWqgs7z/043Yo7MwJyoN4rtAmoLDLikwuzU5Na7nx6qzneJDhTgjjuVs66cPoGJwV9nQvYu9/4JWmX+sAMtXDCfveyYUhHntv1rseiIaDLR+/L3U12A8JLonhvrHbDqXKMx3ZAzMl+MOzPy6tl8R5Hc=
