language: php
php:
- '7.0'
- '7.1'
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
install:
- composer install
- composer require "satooshi/php-coveralls" "^1" --dev --no-update
- "./frameworks/phifty/travis/install"
before_script:
- "./frameworks/phifty/travis/before_script"
- phpenv rehash
- "./travis/before_script"
- php vendor/bin/phifty asset --link
script:
- time php bootstrap.php
- phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
  - exts
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: RuG7og7auWpHm3rDLWv9qHQMYmehEPzOc9Dm7YuL20ieiYxn9CBUERsDPiNaSd3vrG7zrDnSadPB4rfQZpegCwueAb4H2nIdIG90iL8c4E0VFb7F1GtxDtyPT4cz2aOb/Qjav7QQxRaHu94ECnR7h+zcoIN3wdreZ7dAG6INgEcBeDAy4dPc8Hi+uj9/xPVFKLdMy0ouWLmJ8YUEvprc5/OshlYyLznNKfWq7OxCP+x8HPunFlviQWbnmKFBbbo3g6K6JGgyzzSZwqe5xuUmBTYnvM9QcG5iDh3T6MZBa1rUoTbhqnEL76BsVBp+JRh/7D0O9Pws/4HauG6SuK0McEJGv7BGdlh0BLt1er5y8Yti7xq6Puv8VrFZcI/Leu1LRbqg9taXBJ4rgEUM46eB7SYpByQCKxFLGo6HhIMxyeisM3jSl+JE/4+yrnDzIhP/vrJvA14SpQmXFteajyLtZsOsWh9HkI26lVrZv1Q4TRnuxm8D8+xkyrilZPRQmpPX6XLfMuM5RZbg8eclYJm+qstD1nbfKjISF4ZR8RVyg2ahitQTA0YwJuJKGmoZYVpHH1gdNXTRRsF/WWluYcikANH+bUZEkJqgqbn2wUWU3HvrokwXDiC+d1Fne1g8RWvj0BSHQuGL/o/5fkzVkQViOhLhi2Ynomr3x9cHNIEJf24=
